### ISSUE TITLE
Update compose to the latest version

### ISSUE THREAD

**Issue by deepakgahlot98** [vanpra/compose-material-dialogs#26]
With the new version of the Jetpack compose Alpha 11. There is a crash while opening the Dialog.

`java.lang.NoSuchMethodError: No static method rememberMeasureBlocks(Landroidx/compose/ui/Alignment;Landroidx/compose/runtime/Composer;I)Landroidx/compose/ui/node/MeasureBlocks; in class Landroidx/compose/foundation/layout/BoxKt; or its super classes (declaration of 'androidx.compose.foundation.layout.BoxKt' appears in /data/app/com.sap.ariba.mint-WOSP5E9h7725q-wmcj6Qhw==/base.apk)`

**Comment by vanpra** [comment]
There are quite a lot a changes in alpha 11 which break some parts of this library so it will probably take me a couple of days to get through them all. Should be done by the end of the weekend.

**Comment by vanpra** [comment]
It looks like there's a bug with `FlingConfig`'s which means that scrolling doesn't stop at the defined anchor points. This probably means that I can't update this library to alpha11 as lots of key components such as date picker make use of this component. I'll try and have a look to see if there's a temporary workaround but it looks like this might already be fixed in the next version as they've rewritten `FlingConfig` to use the the new suspending transitions API.

**Comment by deepakgahlot98** [comment]
There is a newer version of Jetpack compose Alpha.
https://developer.android.com/jetpack/androidx/releases/compose-material#1.0.0-alpha12

Hope that issue with FlingConfig is resolved in this

**Comment by vanpra** [comment]
I've had another look and it seems like the `FlingConfig` is still broken. However I have been playing around with the snapshot builds of compose and it looks like this issue is fixed as they've replaced `FlingConfig` with `FlingBehavior` and this seems to work as expected. This means that I won't be able to update the library to compose alpha12. However, I've already started migrating the code using the snapshot builds so I should be able to release a new version as soon as alpha13 comes out in a couple of weeks.

**Comment by ln-12** [comment]
Hey @vanpra, [1.0.0-beta01](https://developer.android.com/jetpack/androidx/releases/compose-ui#1.0.0-beta01) is out now :)

**Comment by vanpra** [comment]
Thanks for letting me know @ln-12. I'm still working on migrating some parts of the date and time picker dialogs to the new version which will probably be another day or so. Should have the new version out at some point tomorrow or Sunday.

**Comment by vanpra** [comment]
Library has been updated to 1.0.0-beta01.
